import type { Metadata } from "next";
import "./globals.css";
import NaveBare from "./Component/NavBare/NaveBare";
import { AppWrapper } from "./Context";
import { Bounce, ToastContainer } from "react-toastify";
import LoadingSpinner from "./Component/LoadingSpinner/LoadingSpinner";



export const metadata: Metadata = {
  title: "Maze",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body >
        <AppWrapper>

        <div className="w-screen h-screen overflow-hidden">
          <NaveBare/>
          {children}
        </div>
      <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
        transition={Bounce}
        />
        {

        }
        </AppWrapper>
        
      </body>
    </html>
  );
}
